- name: Get deb architecture
  ansible.builtin.command:
    cmd: 'dpkg --print-architecture'
  register: deb_architecture
  changed_when: false

- name: Get OS version
  ansible.builtin.command:
    cmd: 'lsb_release -cs'
  register: os_version_codename
  changed_when: false

- name: Capture deb architecture
  ansible.builtin.set_fact:
    deb_architecture: "{{ deb_architecture.stdout }}"
    os_version_codename: "{{ os_version_codename.stdout }}"
    docker_repo_url: "https://download.docker.com/linux/ubuntu"

- name: Install docker pre-dependencies
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    name:
      - ca-certificates

- name: Create keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '755'
    owner: root
    group: root

- name: Download docker GPG key
  become: true
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Add Docker repository to sources.list.d
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }} {{ os_version_codename }} stable"
    state: present

- name: Install docker
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Install docker daemon config
  become: true
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  vars:
    registry_host1: "{{ registry_ip }}:5000"
    registry_host2: "{{ registry_ip }}:6000"
  notify: restart docker
