[package]
name = "exploit-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.7.0"
backon = "0.4.0"
celery = "0.5.3"
common = { path = "../common" }
diesel = { version = "2", features = ["postgres", "uuid", "r2d2", "chrono"] }
dotenv = "0.15"
env_logger = "0.10"
exploit-runner = { path = "../exploit-runner" }
flate2 = "1.0.25"
lazy_static = "1.4.0"
log = "0.4.17"
nix = "0.26.2"
num_cpus = "1.15.0"
object_store = { version = "0.7.0", features = ["aws", "azure", "gcp"] }
serde = "1.0.152"
tar = "0.4.38"
tempfile = "3.8.0"
tokio = "1.24.1"
uuid = { version = "1", features = ["v4", "serde"] }
