- name: Create LiveCTF user
  become: true
  ansible.builtin.user:
    name: livectf
    comment: LiveCTF
    create_home: true
    home: /opt/livectf
    system: true
    state: present

- name: Set subuids
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subuid 
    regex: "^livectf"
    line: "livectf:100000:65536"
    create: true
    mode: '644'
    owner: root
    group: root

- name: Set subgids
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subgid 
    regex: "^livectf"
    line: "livectf:100000:65536"
    create: true
    mode: '644'
    owner: root
    group: root

- name: Pull the LiveCTF builder image
  become: true
  become_user: livectf
  containers.podman.podman_image:
    name: localhost:5001/livectf-builder
    state: present
    validate_certs: false
    force: "{{ upgrade_builder | default(false) | bool }}"

- name: Create a directory for sharing credentials
  become: true
  ansible.builtin.file:
    state: directory
    path: /var/lib/livectf/credentials
    owner: "100999"
    group: "100999"
    mode: '755'

- name: Start LiveCTF builder container
  become: true
  become_user: livectf
  containers.podman.podman_container:
    name: livectf-builder
    image: localhost:5001/livectf-builder
    recreate: "{{ upgrade_builder | default(false) | bool }}"
    state: started
    user: podman
    privileged: true
    env:
      BUILD_PATH: "{{ build_path }}"
      EXPLOITS_PATH: "{{ exploits_path }}"
      EXPLOITS_STORAGE: "{{ exploits_storage }}"
      AMQP_ADDR: "amqp://{{ amqp_username }}:{{ amqp_password }}@{{ rabbitmq_ip }}//"
      DATABASE_URL: "postgres://{{ database_username }}:{{ database_password }}@{{ database_ip }}/{{ database_db }}"
      DOCKER_REPO: "{{ registry_ip }}:5000/"
      GOOGLE_SERVICE_ACCOUNT_KEY: "{{ gcp_service_account_key_reader | string }}"
      RUST_LOG: info
      DOCKER_DISK_LIMIT: "1"
      CONTAINER_RUNNER: "podman"
    volumes:
      - /var/lib/livectf/credentials:/credentials
